alias venvactive='source venv/bin/activate'
alias venvhere='python3 -m venv ./venv'
alias calamar='cd ~/calamar'
alias disney='cd ~/calamar/disneyworld'
alias dashboard='cd ~/calamar/dashboard_umbrella'
alias fetchpull='git fetch && git pull origin master'
alias devdb='psql dashboard_dev'
